export const englishIngredients = {
  tomato: { singular: "tomato", plural: "tomatoes" },
  garlic: { singular: "garlic", plural: "garlic" },
  egg: { singular: "egg", plural: "eggs" },
  flour: { singular: "flour", plural: "flour" },
  sugar: { singular: "sugar", plural: "sugar" },
  salt: { singular: "salt", plural: "salt" },
  water: { singular: "water", plural: "water" },
  milk: { singular: "milk", plural: "milk" },
  bakingSoda: { singular: "baking soda", plural: "baking soda" },
  bakingPowder: { singular: "baking powder", plural: "baking powder" },
  yeast: { singular: "yeast", plural: "yeast" },
  whiteSugar: { singular: "white sugar", plural: "white sugar" },
  brownSugar: { singular: "brown sugar", plural: "brown sugar" },
  seaSalt: { singular: "sea salt", plural: "sea salt" },
  butter: { singular: "butter", plural: "butter" },
  oil: { singular: "oil", plural: "oil" },
  vegetableOil: { singular: "vegetable oil", plural: "vegetable oil" },
  oliveOil: { singular: "olive oil", plural: "olive oil" },
  vanillaExtract: { singular: "vanilla extract", plural: "vanilla extract" },
  lemonJuice: { singular: "lemon juice", plural: "lemon juice" },
  limeJuice: { singular: "lime juice", plural: "lime juice" },
  orangeJuice: { singular: "orange juice", plural: "orange juice" },
  lemonZest: { singular: "lemon zest", plural: "lemon zest" },
  limeZest: { singular: "lime zest", plural: "lime zest" },
  orangeZest: { singular: "orange zest", plural: "orange zest" },
  lemon: { singular: "lemon", plural: "lemons" },
  lime: { singular: "lime", plural: "limes" },
  orange: { singular: "orange", plural: "oranges" },
  apple: { singular: "apple", plural: "apples" },
  banana: { singular: "banana", plural: "bananas" },
  pear: { singular: "pear", plural: "pears" },
  chocolate: { singular: "chocolate", plural: "chocolate" },
  cocoaPowder: { singular: "cocoa powder", plural: "cocoa powder" },
  coffee: { singular: "coffee", plural: "coffee" },
  tea: { singular: "tea", plural: "tea" },
  cinnamon: { singular: "cinnamon", plural: "cinnamon" },
  ginger: { singular: "ginger", plural: "ginger" },
  nutmeg: { singular: "nutmeg", plural: "nutmeg" },
  cardamom: { singular: "cardamom", plural: "cardamom" },
  blackPepper: { singular: "black pepper", plural: "black pepper" },
  cayennePepper: { singular: "cayenne pepper", plural: "cayenne pepper" },
  whitePepper: { singular: "white pepper", plural: "white pepper" },
  paprika: { singular: "paprika", plural: "paprika" },
  basil: { singular: "basil", plural: "basil" },
  oregano: { singular: "oregano", plural: "oregano" },
  pizzaDough: { singular: "pizza dough", plural: "pizza dough" },
  pastaDough: { singular: "pasta dough", plural: "pasta dough" },
  pasta: { singular: "pasta", plural: "pasta" },
  rice: { singular: "rice", plural: "rice" },
  couscous: { singular: "couscous", plural: "couscous" },
  potato: { singular: "potato", plural: "potatoes" },
  sweetPotato: { singular: "sweet potato", plural: "sweet potatoes" },
  onion: { singular: "onion", plural: "onions" },
  redOnion: { singular: "red onion", plural: "red onions" },
  springOnion: { singular: "spring onion", plural: "spring onions" },
  salmon: { singular: "salmon", plural: "salmon" },
  tuna: { singular: "tuna", plural: "tuna" },
  cod: { singular: "cod", plural: "cod" },
  haddock: { singular: "haddock", plural: "haddock" },
  chicken: { singular: "chicken", plural: "chicken" },
  chickenBreast: { singular: "chicken breast", plural: "chicken breasts" },
  chickenThigh: { singular: "chicken thigh", plural: "chicken thighs" },
  chickenWing: { singular: "chicken wing", plural: "chicken wings" },
  beef: { singular: "beef", plural: "beef" },
  steak: { singular: "steak", plural: "steak" },
  pork: { singular: "pork", plural: "pork" },
  bacon: { singular: "bacon", plural: "bacon" },
  sausage: { singular: "sausage", plural: "sausage" },
  chocolateChip: { singular: "chocolate chip", plural: "chocolate chips" },
  chocolateBar: { singular: "chocolate bar", plural: "chocolate bars" },
  mapleSyrup: { singular: "maple syrup", plural: "maple syrup" },
  honey: { singular: "honey", plural: "honey" },
  jam: { singular: "jam", plural: "jam" },
  peanutButter: { singular: "peanut butter", plural: "peanut butter" },
  almondButter: { singular: "almond butter", plural: "almond butter" },
  strawberryJam: { singular: "strawberry jam", plural: "strawberry jam" },
  raspberryJam: { singular: "raspberry jam", plural: "raspberry jam" },
  blueberryJam: { singular: "blueberry jam", plural: "blueberry jam" },
  blackberryJam: { singular: "blackberry jam", plural: "blackberry jam" },
  apricotJam: { singular: "apricot jam", plural: "apricot jam" },
  peanut: { singular: "peanut", plural: "peanuts" },
  almond: { singular: "almond", plural: "almonds" },
  walnut: { singular: "walnut", plural: "walnuts" },
  pecan: { singular: "pecan", plural: "pecans" },
  cashew: { singular: "cashew", plural: "cashews" },
  hazelnut: { singular: "hazelnut", plural: "hazelnuts" },
  strawberry: { singular: "strawberry", plural: "strawberries" },
  raspberry: { singular: "raspberry", plural: "raspberries" },
  blueberry: { singular: "blueberry", plural: "blueberries" },
  blackberry: { singular: "blackberry", plural: "blackberries" },
  apricot: { singular: "apricot", plural: "apricots" },
  peach: { singular: "peach", plural: "peaches" },
  plum: { singular: "plum", plural: "plums" },
  cherry: { singular: "cherry", plural: "cherries" },
  cream: { singular: "cream", plural: "cream" },
  vinegar: { singular: "vinegar", plural: "vinegar" },
  chickenStock: { singular: "chicken stock", plural: "chicken stock" },
  chickenBroth: { singular: "chicken broth", plural: "chicken broth" },
  beefStock: { singular: "beef stock", plural: "beef stock" },
  beefBroth: { singular: "beef broth", plural: "beef broth" },
  vegetableStock: { singular: "vegetable stock", plural: "vegetable stock" },
  vegetableBroth: { singular: "vegetable broth", plural: "vegetable broth" },
  fishStock: { singular: "fish stock", plural: "fish stock" },
  fishBroth: { singular: "fish broth", plural: "fish broth" },
  cannedTomato: { singular: "canned tomato", plural: "canned tomatoes" },
  tomatoSauce: { singular: "tomato sauce", plural: "tomato sauce" },
  tomatoPaste: { singular: "tomato paste", plural: "tomato paste" },
  ketchup: { singular: "ketchup", plural: "ketchup" },
  mustard: { singular: "mustard", plural: "mustard" },
  mayonnaise: { singular: "mayonnaise", plural: "mayonnaise" },
  soySauce: { singular: "soy sauce", plural: "soy sauce" },
  worcestershireSauce: {
    singular: "worcestershire sauce",
    plural: "worcestershire sauce",
  },
  tabascoSauce: { singular: "tabasco sauce", plural: "tabasco sauce" },
  hotSauce: { singular: "hot sauce", plural: "hot sauce" },
  barbecueSauce: { singular: "barbecue sauce", plural: "barbecue sauce" },
  beans: { singular: "bean", plural: "beans" },
  whiteBeans: { singular: "white bean", plural: "white beans" },
  blackBeans: { singular: "black bean", plural: "black beans" },
  kidneyBeans: { singular: "kidney bean", plural: "kidney beans" },
  chickpeas: { singular: "chickpea", plural: "chickpeas" },
  lentils: { singular: "lentil", plural: "lentils" },
  breadcrumbs: { singular: "breadcrumb", plural: "breadcrumbs" },
  driedBasil: { singular: "dried basil", plural: "dried basil" },
  driedOregano: { singular: "dried oregano", plural: "dried oregano" },
  bayLeaves: { singular: "bay leaf", plural: "bay leaves" },
  driedThyme: { singular: "dried thyme", plural: "dried thyme" },
  driedRosemary: { singular: "dried rosemary", plural: "dried rosemary" },
  driedParsley: { singular: "dried parsley", plural: "dried parsley" },
  driedDill: { singular: "dried dill", plural: "dried dill" },
  curryPowder: { singular: "curry powder", plural: "curry powder" },
  cumin: { singular: "cumin", plural: "cumin" },
  chiliPowder: { singular: "chili powder", plural: "chili powder" },
  chiliFlakes: { singular: "chili flake", plural: "chili flakes" },
  onionPowder: { singular: "onion powder", plural: "onion powder" },
  parsley: { singular: "parsley", plural: "parsley" },
  margarine: { singular: "margarine", plural: "margarine" },
  cheese: { singular: "cheese", plural: "cheese" },
  cheddar: { singular: "cheddar cheese", plural: "cheddar cheese" },
  mozzarella: { singular: "mozzarella cheese", plural: "mozzarella cheese" },
  parmesan: { singular: "parmesan cheese", plural: "parmesan cheese" },
  fetaCheese: { singular: "feta cheese", plural: "feta cheese" },
  goatCheese: { singular: "goat cheese", plural: "goat cheese" },
  creamCheese: { singular: "cream cheese", plural: "cream cheese" },
  sourCream: { singular: "sour cream", plural: "sour cream" },
  yogurt: { singular: "yogurt", plural: "yogurt" },
  cornstarch: { singular: "cornstarch", plural: "cornstarch" },
  corn: { singular: "corn", plural: "corn" },
  spinach: { singular: "spinach", plural: "spinach" },
  kale: { singular: "kale", plural: "kale" },
  peas: { singular: "pea", plural: "peas" },
  broccoli: { singular: "broccoli", plural: "broccoli" },
  cauliflower: { singular: "cauliflower", plural: "cauliflower" },
  asparagus: { singular: "asparagus", plural: "asparagus" },
  brusselsSprouts: { singular: "brussels sprout", plural: "brussels sprouts" },
  cabbage: { singular: "cabbage", plural: "cabbage" },
  lettuce: { singular: "lettuce", plural: "lettuce" },
  celery: { singular: "celery", plural: "celery" },
  carrot: { singular: "carrot", plural: "carrots" },
  shallot: { singular: "shallot", plural: "shallots" },
  horseradish: { singular: "horseradish", plural: "horseradish" },
  cookingSpray: { singular: "cooking spray", plural: "cooking spray" },
  canolaOil: { singular: "canola oil", plural: "canola oil" },
  redWine: { singular: "red wine", plural: "red wine" },
  whiteWine: { singular: "white wine", plural: "white wine" },
  beer: { singular: "beer", plural: "beer" },
  vodka: { singular: "vodka", plural: "vodka" },
  rum: { singular: "rum", plural: "rum" },
  gin: { singular: "gin", plural: "gin" },
  tequila: { singular: "tequila", plural: "tequila" },
  whiskey: { singular: "whiskey", plural: "whiskey" },
  bourbon: { singular: "bourbon", plural: "bourbon" },
  scotch: { singular: "scotch", plural: "scotch" },
  coconutMilk: { singular: "coconut milk", plural: "coconut milk" },
  coconutCream: { singular: "coconut cream", plural: "coconut cream" },
  coconutOil: { singular: "coconut oil", plural: "coconut oil" },
  mushrooms: { singular: "mushroom", plural: "mushrooms" },
  portobelloMushrooms: {
    singular: "portobello mushroom",
    plural: "portobello mushrooms",
  },
  groundBeef: { singular: "ground beef", plural: "ground beef" },
  groundPork: { singular: "ground pork", plural: "ground pork" },
  tortilla: { singular: "tortilla", plural: "tortillas" },
  tortillaChips: { singular: "tortilla chip", plural: "tortilla chips" },
  garamMasala: { singular: "garam masala", plural: "garam masala" },
  beetroot: { singular: "beetroot", plural: "beetroots" },
  coffeeBeans: { singular: "coffee bean", plural: "coffee beans" },
  pumpkin: { singular: "pumpkin", plural: "pumpkins" },
  watermelon: { singular: "watermelon", plural: "watermelons" },
  cantaloupe: { singular: "cantaloupe", plural: "cantaloupes" },
  honeydew: { singular: "honeydew", plural: "honeydews" },
  mango: { singular: "mango", plural: "mangos" },
  pineapple: { singular: "pineapple", plural: "pineapples" },
  spaghetti: { singular: "spaghetti", plural: "spaghetti" },
  linguine: { singular: "linguine", plural: "linguine" },
  fettuccine: { singular: "fettuccine", plural: "fettuccine" },
  donut: { singular: "donut", plural: "donuts" },
  bagel: { singular: "bagel", plural: "bagels" },
  croissant: { singular: "croissant", plural: "croissants" },
  muffin: { singular: "muffin", plural: "muffins" },
  bread: { singular: "bread", plural: "bread" },
  pita: { singular: "pita", plural: "pita" },
  naan: { singular: "naan", plural: "naan" },
  baguette: { singular: "baguette", plural: "baguettes" },
  focaccia: { singular: "focaccia", plural: "focaccia" },
  ryeBread: { singular: "rye bread", plural: "rye bread" },
  kiwifruit: { singular: "kiwifruit", plural: "kiwifruit" },
  grapefruit: { singular: "grapefruit", plural: "grapefruit" },
  avocado: { singular: "avocado", plural: "avocados" },
  papaya: { singular: "papaya", plural: "papayas" },
  pomegranate: { singular: "pomegranate", plural: "pomegranates" },
  cranberry: { singular: "cranberry", plural: "cranberries" },
  guava: { singular: "guava", plural: "guavas" },
  cloudberry: { singular: "cloudberry", plural: "cloudberry" },
  dragonfruit: { singular: "dragonfruit", plural: "dragonfruit" },
  raisin: { singular: "raisin", plural: "raisins" },
  clementine: { singular: "clementine", plural: "clementines" },
  tangerine: { singular: "tangerine", plural: "tangerines" },
  mandarin: { singular: "mandarin", plural: "mandarins" },
  passionfruit: { singular: "passionfruit", plural: "passionfruit" },
  jalapeno: { singular: "jalapeño", plural: "jalapeños" },
  habanero: { singular: "habanero", plural: "habaneros" },
  shrimp: { singular: "shrimp", plural: "shrimp" },
  lobster: { singular: "lobster", plural: "lobster" },
  crab: { singular: "crab", plural: "crab" },
  scallop: { singular: "scallop", plural: "scallops" },
  oyster: { singular: "oyster", plural: "oysters" },
  mussel: { singular: "mussel", plural: "mussels" },
  clam: { singular: "clam", plural: "clams" },
  octopus: { singular: "octopus", plural: "octopus" },
  squid: { singular: "squid", plural: "squid" },
  snail: { singular: "snail", plural: "snails" },
  anchovy: { singular: "anchovy", plural: "anchovies" },
  sardine: { singular: "sardine", plural: "sardines" },
  trout: { singular: "trout", plural: "trout" },
  catfish: { singular: "catfish", plural: "catfish" },
  tilapia: { singular: "tilapia", plural: "tilapia" },
  halibut: { singular: "halibut", plural: "halibut" },
  swordfish: { singular: "swordfish", plural: "swordfish" },
} as const;
