import type { IngredientType } from "./ingredientTranslator";

export const finnishIngredients = {
  tomato: { singular: "tomaatti", plural: "tomaattia" },
  garlic: { singular: "valkosipuli", plural: "valkosipulia" },
  egg: { singular: "kananmuna", plural: "kananmunaa" },
  flour: { singular: "vehnäjauho", plural: "vehnäjauhoa" },
  sugar: { singular: "sokeri", plural: "sokeria" },
  salt: { singular: "suola", plural: "suolaa" },
  water: { singular: "vesi", plural: "vettä" },
  milk: { singular: "maito", plural: "maitoa" },
  bakingSoda: { singular: "ruokasooda", plural: "ruokasoodaa" },
  bakingPowder: { singular: "leivinjauhe", plural: "leivinjauhetta" },
  yeast: { singular: "hiiva", plural: "hiivaa" },
  whiteSugar: { singular: "valkoinen sokeri", plural: "valkoista sokeria" },
  brownSugar: { singular: "ruskea sokeri", plural: "ruskeaa sokeria" },
  seaSalt: { singular: "merisuola", plural: "merisuolaa" },
  butter: { singular: "voi", plural: "voita" },
  oil: { singular: "öljy", plural: "öljyä" },
  vegetableOil: { singular: "kasviöljy", plural: "kasviöljyä" },
  oliveOil: { singular: "oliiviöljy", plural: "oliiviöljyä" },
  vanillaExtract: { singular: "vanilja", plural: "vaniljaa" },
  lemonJuice: { singular: "sitruunamehu", plural: "sitruunamehua" },
  limeJuice: { singular: "limettimehu", plural: "limettimehua" },
  orangeJuice: { singular: "appelsiinimehu", plural: "appelsiinimehua" },
  lemonZest: { singular: "sitruunan kuori", plural: "sitruunan kuorta" },
  limeZest: { singular: "limen kuori", plural: "limen kuorta" },
  orangeZest: { singular: "appelsiinin kuori", plural: "appelsiinin kuorta" },
  lemon: { singular: "sitruuna", plural: "sitruunaa" },
  lime: { singular: "lime", plural: "limeä" },
  orange: { singular: "appelsiini", plural: "appelsiinia" },
  apple: { singular: "omena", plural: "omenaa" },
  banana: { singular: "banaani", plural: "banaania" },
  pear: { singular: "päärynä", plural: "päärynää" },
} satisfies Record<IngredientType, { singular: string; plural: string }>;
