import type { IngredientType } from "./ingredientTranslator";

export const finnishIngredients = {
  tomato: { singular: "tomaatti", plural: "tomaattia" },
  garlic: { singular: "valkosipuli", plural: "valkosipulia" },
  egg: { singular: "kananmuna", plural: "kananmunaa" },
  flour: { singular: "vehnäjauho", plural: "vehnäjauhoa" },
  sugar: { singular: "sokeri", plural: "sokeria" },
  salt: { singular: "suola", plural: "suolaa" },
  water: { singular: "vesi", plural: "vettä" },
  milk: { singular: "maito", plural: "maitoa" },
  bakingSoda: { singular: "ruokasooda", plural: "ruokasoodaa" },
  bakingPowder: { singular: "leivinjauhe", plural: "leivinjauhetta" },
  yeast: { singular: "hiiva", plural: "hiivaa" },
  whiteSugar: { singular: "valkoinen sokeri", plural: "valkoista sokeria" },
  brownSugar: { singular: "ruskea sokeri", plural: "ruskeaa sokeria" },
  seaSalt: { singular: "merisuola", plural: "merisuolaa" },
  butter: { singular: "voi", plural: "voita" },
  oil: { singular: "öljy", plural: "öljyä" },
  vegetableOil: { singular: "kasviöljy", plural: "kasviöljyä" },
  oliveOil: { singular: "oliiviöljy", plural: "oliiviöljyä" },
  vanillaExtract: { singular: "vanilja", plural: "vaniljaa" },
  lemonJuice: { singular: "sitruunamehu", plural: "sitruunamehua" },
  limeJuice: { singular: "limettimehu", plural: "limettimehua" },
  orangeJuice: { singular: "appelsiinimehu", plural: "appelsiinimehua" },
  lemonZest: { singular: "sitruunan kuori", plural: "sitruunan kuorta" },
  limeZest: { singular: "limen kuori", plural: "limen kuorta" },
  orangeZest: { singular: "appelsiinin kuori", plural: "appelsiinin kuorta" },
  lemon: { singular: "sitruuna", plural: "sitruunaa" },
  lime: { singular: "lime", plural: "limeä" },
  orange: { singular: "appelsiini", plural: "appelsiinia" },
  apple: { singular: "omena", plural: "omenaa" },
  banana: { singular: "banaani", plural: "banaania" },
  pear: { singular: "päärynä", plural: "päärynää" },
  chocolate: { singular: "suklaa", plural: "suklaata" },
  cocoaPowder: { singular: "kaakaojauhe", plural: "kaakaojauhetta" },
  coffee: { singular: "kahvi", plural: "kahvia" },
  tea: { singular: "tee", plural: "teetä" },
  cinnamon: { singular: "kaneli", plural: "kanelia" },
  ginger: { singular: "inkivääri", plural: "inkivääriä" },
  nutmeg: { singular: "muskottipähkinä", plural: "muskottipähkinää" },
  cardamom: { singular: "kardemumma", plural: "kardemummaa" },
  blackPepper: { singular: "mustapippuri", plural: "mustapippuria" },
  cayennePepper: { singular: "cayennepippuri", plural: "cayennepippuria" },
  whitePepper: { singular: "valkopippuri", plural: "valkopippuria" },
  paprika: { singular: "paprika", plural: "paprika" },
  basil: { singular: "basilika", plural: "basilikaa" },
  oregano: { singular: "oregano", plural: "oregano" },
  pizzaDough: { singular: "pitsataikina", plural: "pitsataikinaa" },
  pastaDough: { singular: "pastataikina", plural: "pastataikinaa" },
  pasta: { singular: "pasta", plural: "pastaa" },
  rice: { singular: "riisi", plural: "riisiä" },
  couscous: { singular: "kuskus", plural: "kuskusta" },
  potato: { singular: "peruna", plural: "perunaa" },
  sweetPotato: { singular: "bataatti", plural: "bataattia" },
  onion: { singular: "sipuli", plural: "sipulia" },
  redOnion: { singular: "punasipuli", plural: "punasipulia" },
  springOnion: { singular: "kevätsipuli", plural: "kevätsipulia" },
  salmon: { singular: "lohi", plural: "lohta" },
  tuna: { singular: "tonnikala", plural: "tonnikalaa" },
  cod: { singular: "turska", plural: "turskaa" },
  haddock: { singular: "kolja", plural: "koljaa" },
  chicken: { singular: "kana", plural: "kanaa" },
  chickenBreast: { singular: "kananrinta", plural: "kananrintaa" },
  chickenThigh: { singular: "kanankoipi", plural: "kanankoipia" },
  chickenWing: { singular: "kanansiipi", plural: "kanansiipiä" },
  beef: { singular: "naudanliha", plural: "naudanlihaa" },
  steak: { singular: "pihvi", plural: "pihviä" },
  pork: { singular: "sianliha", plural: "sianlihaa" },
  bacon: { singular: "pekoni", plural: "pekonia" },
  sausage: { singular: "nakkimakkara", plural: "nakkimakkaraa" },
  chocolateChip: { singular: "suklaahippu", plural: "suklaahippuja" },
  chocolateBar: { singular: "suklaalevy", plural: "suklaalevyjä" },
  mapleSyrup: { singular: "vaahterasiirappi", plural: "vaahterasiirappia" },
  honey: { singular: "hunaja", plural: "hunajaa" },
  jam: { singular: "hillo", plural: "hilloa" },
  peanutButter: { singular: "maapähkinävoi", plural: "maapähkinävoita" },
  almondButter: { singular: "mantelivoi", plural: "mantelivoita" },
  strawberryJam: { singular: "mansikkahillo", plural: "mansikkahilloa" },
  raspberryJam: { singular: "vadelmahillo", plural: "vadelmahilloa" },
  blueberryJam: { singular: "mustikkahillo", plural: "mustikkahilloa" },
  blackberryJam: {
    singular: "karhunvatukkahillo",
    plural: "karhunvatukkahilloa",
  },
  apricotJam: { singular: "aprikoosihillo", plural: "aprikoosihilloa" },
  peanut: { singular: "maapähkinä", plural: "maapähkinöitä" },
  almond: { singular: "manteli", plural: "manteleita" },
  walnut: { singular: "saksanpähkinä", plural: "saksanpähkinöitä" },
  pecan: { singular: "pekaanipähkinä", plural: "pekaanipähkinöitä" },
  cashew: { singular: "cashewpähkinä", plural: "cashewpähkinöitä" },
  hazelnut: { singular: "hasselpähkinä", plural: "hasselpähkinöitä" },
  strawberry: { singular: "mansikka", plural: "mansikoita" },
  raspberry: { singular: "vadelma", plural: "vadelmia" },
  blueberry: { singular: "mustikka", plural: "mustikoita" },
  blackberry: { singular: "karhunvatukka", plural: "karhunvatukoita" },
  apricot: { singular: "aprikoosi", plural: "aprikooseja" },
  peach: { singular: "persikka", plural: "persikoita" },
  plum: { singular: "luumu", plural: "luumuja" },
  cherry: { singular: "kirsikka", plural: "kirsikoita" },
  cream: { singular: "kerma", plural: "kermaa" },
  vinegar: { singular: "etikka", plural: "etikkaa" },
  chickenStock: { singular: "kanaliemi", plural: "kanalientä" },
  chickenBroth: { singular: "kanaliemi", plural: "kanalientä" },
  beefStock: { singular: "lihaliemi", plural: "lihalientä" },
  beefBroth: { singular: "lihaliemi", plural: "lihalientä" },
  vegetableStock: { singular: "kasvisliemi", plural: "kasvislientä" },
  vegetableBroth: { singular: "kasvisliemi", plural: "kasvislientä" },
  fishStock: { singular: "kalaliemi", plural: "kalalientä" },
  fishBroth: { singular: "kalaliemi", plural: "kalalientä" },
  cannedTomato: { singular: "säilyketomaatti", plural: "säilyketomaatteja" },
  tomatoSauce: { singular: "tomaattikastike", plural: "tomaattikastiketta" },
  tomatoPaste: { singular: "tomaattisose", plural: "tomaattisosetta" },
  ketchup: { singular: "ketsuppi", plural: "ketsuppia" },
  mustard: { singular: "sinappi", plural: "sinappia" },
  mayonnaise: { singular: "majoneesi", plural: "majoneesia" },
  soySauce: { singular: "soijakastike", plural: "soijakastiketta" },
  worcestershireSauce: {
    singular: "worcesterkastike",
    plural: "worcesterkastiketta",
  },
  tabascoSauce: { singular: "tabascokastike", plural: "tabascokastiketta" },
  hotSauce: { singular: "tulinen kastike", plural: "tulista kastiketta" },
  barbecueSauce: { singular: "barbequekastike", plural: "barbequekastiketta" },
  beans: { singular: "papu", plural: "papuja" },
  whiteBeans: { singular: "valkopapu", plural: "valkopapuja" },
  blackBeans: { singular: "mustapapu", plural: "mustapapuja" },
  kidneyBeans: { singular: "kidneypapu", plural: "kidneypapuja" },
  chickpeas: { singular: "kikherne", plural: "kikherneitä" },
  lentils: { singular: "linssi", plural: "linssejä" },
  breadcrumbs: { singular: "korppujauho", plural: "korppujauhoja" },
  driedBasil: { singular: "kuivattu basilika", plural: "kuivattua basilikaa" },
  driedOregano: { singular: "kuivattu oregano", plural: "kuivattua oreganoa" },
  bayLeaves: { singular: "laakerinlehti", plural: "laakerinlehteä" },
  driedThyme: { singular: "kuivattu timjami", plural: "kuivattua timjamia" },
  driedRosemary: {
    singular: "kuivattu rosmariini",
    plural: "kuivattua rosmariinia",
  },
  driedParsley: {
    singular: "kuivattu persilja",
    plural: "kuivattua persiljaa",
  },
  driedDill: { singular: "kuivattu tilli", plural: "kuivattua tilliä" },
  curryPowder: { singular: "curry", plural: "currya" },
  cumin: { singular: "kumina", plural: "kuminaa" },
  chiliPowder: { singular: "chilijauhe", plural: "chilijauhetta" },
  chiliFlakes: { singular: "chilihiutale", plural: "chilihiutaleita" },
  onionPowder: { singular: "sipulijauhe", plural: "sipulijauhetta" },
  parsley: { singular: "persilja", plural: "persiljaa" },
  margarine: { singular: "margariini", plural: "margariinia" },
  cheese: { singular: "juusto", plural: "juustoa" },
  cheddar: { singular: "cheddarjuusto", plural: "cheddarjuustoa" },
  mozzarella: { singular: "mozzarellajuusto", plural: "mozzarellajuustoa" },
  parmesan: { singular: "parmesanjuusto", plural: "parmesanjuustoa" },
  fetaCheese: { singular: "fetajuusto", plural: "fetajuustoa" },
  goatCheese: { singular: "vuohenjuusto", plural: "vuohenjuustoa" },
  creamCheese: { singular: "tuorejuusto", plural: "tuorejuustoa" },
  sourCream: { singular: "hapankerma", plural: "hapankermaa" },
  yogurt: { singular: "jogurtti", plural: "jogurtti" },
  cornstarch: { singular: "maissitärkkelys", plural: "maissitärkkelystä" },
  corn: { singular: "maissi", plural: "maissia" },
  spinach: { singular: "pinaatti", plural: "pinaattia" },
  kale: { singular: "lehtikaali", plural: "lehtikaalia" },
  peas: { singular: "herne", plural: "herneitä" },
  broccoli: { singular: "parsakaali", plural: "parsakaalia" },
  cauliflower: { singular: "kukkakaali", plural: "kukkakaalia" },
  asparagus: { singular: "parsa", plural: "parsaa" },
  brusselsSprouts: { singular: "ruusukaali", plural: "ruusukaalia" },
  cabbage: { singular: "kaali", plural: "kaalia" },
  lettuce: { singular: "salaatti", plural: "salaattia" },
  celery: { singular: "selleri", plural: "selleriä" },
  carrot: { singular: "porkkana", plural: "porkkanaa" },
  shallot: { singular: "salottisipuli", plural: "salottisipulia" },
  horseradish: { singular: "piparjuuri", plural: "piparjuurta" },
  cookingSpray: { singular: "vuokaspray", plural: "vuokasprayta" },
  canolaOil: { singular: "rypsiöljy", plural: "rypsiöljyä" },
  redWine: { singular: "punaviini", plural: "punaviiniä" },
  whiteWine: { singular: "valkoviini", plural: "valkoviiniä" },
  beer: { singular: "olut", plural: "olutta" },
  vodka: { singular: "vodka", plural: "vodkaa" },
  rum: { singular: "rommi", plural: "rommia" },
  gin: { singular: "gini", plural: "giniä" },
  tequila: { singular: "tequila", plural: "tequilaa" },
  whiskey: { singular: "viski", plural: "viskiä" },
  bourbon: { singular: "bourbonviski", plural: "bourbonviskiä" },
  scotch: { singular: "skottiviski", plural: "skottiviskiä" },
  coconutMilk: { singular: "kookosmaito", plural: "kookosmaitoa" },
  coconutCream: { singular: "kookoskerma", plural: "kookoskermaa" },
  coconutOil: { singular: "kookosöljy", plural: "kookosöljyä" },
  mushrooms: { singular: "sieni", plural: "sieniä" },
  portobelloMushrooms: {
    singular: "herkkusieni",
    plural: "herkkusieniä",
  },
  groundBeef: { singular: "jauheliha", plural: "jauhelihaa" },
  groundPork: { singular: "porsaan jauheliha", plural: "porsaan jauheliha" },
  tortilla: { singular: "tortilla", plural: "tortillaa" },
  tortillaChips: { singular: "tortillasipsi", plural: "tortillasipsejä" },
  garamMasala: { singular: "garam masala", plural: "garam masalaa" },
  beetroot: { singular: "punajuuri", plural: "punajuurta" },
  coffeeBeans: { singular: "kahvipapu", plural: "kahvipapuja" },
  pumpkin: { singular: "kurpitsa", plural: "kurpitsaa" },
  watermelon: { singular: "vesimeloni", plural: "vesimelonia" },
  cantaloupe: { singular: "verkkomeloni", plural: "verkkomelonia" },
  honeydew: { singular: "hunajameloni", plural: "hunajamelonia" },
  mango: { singular: "mango", plural: "mangoa" },
  pineapple: { singular: "ananas", plural: "ananasta" },
  spaghetti: { singular: "spaghetti", plural: "spaghettia" },
  linguine: { singular: "linguinepasta", plural: "linguinepastaa" },
  fettuccine: { singular: "fettuccinepasta", plural: "fettuccinepastaa" },
  donut: { singular: "donitsi", plural: "donitsia" },
  bagel: { singular: "rinkeli", plural: "rinkeliä" },
  croissant: { singular: "kroissantti", plural: "kroissanttia" },
  muffin: { singular: "muffinssi", plural: "muffinssia" },
  bread: { singular: "leipä", plural: "leipää" },
  pita: { singular: "pitaleipä", plural: "pitaleipää" },
  naan: { singular: "naanleipä", plural: "naanleipää" },
  baguette: { singular: "patonki", plural: "patonkia" },
  focaccia: { singular: "focaccialeipä", plural: "focaccialeipää" },
  ryeBread: { singular: "ruisleipä", plural: "ruisleipää" },
  kiwifruit: { singular: "kiivihedelmä", plural: "kiivihedelmää" },
  grapefruit: { singular: "greippi", plural: "greippiä" },
  avocado: { singular: "avokado", plural: "avokadoa" },
  papaya: { singular: "papaija", plural: "papaijaa" },
  pomegranate: { singular: "granaattiomena", plural: "granaattiomenaa" },
  cranberry: { singular: "karpalo", plural: "karpaloita" },
  guava: { singular: "guava", plural: "guavaa" },
  cloudberry: { singular: "lakka", plural: "lakkoja" },
  dragonfruit: { singular: "pitaija", plural: "pitaijaa" },
  raisin: { singular: "rusina", plural: "rusinoita" },
  clementine: { singular: "klementiini", plural: "klementiinejä" },
  tangerine: { singular: "tangeriini", plural: "tangeriineja" },
  mandarin: { singular: "mandariini", plural: "mandariineja" },
  passionfruit: { singular: "passionhedelmä", plural: "passionhedelmiä" },
  jalapeno: { singular: "jalapeño", plural: "jalapeñoja" },
  habanero: { singular: "habanero", plural: "habaneroja" },
  shrimp: { singular: "katkarapu", plural: "katkarapuja" },
  lobster: { singular: "hummeri", plural: "hummeria" },
  crab: { singular: "rapu", plural: "rapuja" },
  scallop: { singular: "kampasimpukka", plural: "kampasimpukoita" },
  oyster: { singular: "oisteri", plural: "oistereita" },
  mussel: { singular: "simpukka", plural: "simpukoita" },
  clam: { singular: "simpukka", plural: "simpukoita" },
  octopus: { singular: "mustekala", plural: "mustekalaa" },
  squid: { singular: "mustekala", plural: "mustekalaa" },
  snail: { singular: "etana", plural: "etanoita" },
  anchovy: { singular: "sardelli", plural: "sardelleja" },
  sardine: { singular: "sardiini", plural: "sardiineja" },
  trout: { singular: "taimen", plural: "taimenia" },
  catfish: { singular: "monni", plural: "monnia" },
  tilapia: { singular: "tilapia", plural: "tilapiaa" },
  halibut: { singular: "ruijanpallas", plural: "ruijanpallasta" },
  swordfish: { singular: "miekkakala", plural: "miekkakalaa" },
} satisfies Record<IngredientType, { singular: string; plural: string }>;
