export const englishIngredients = {
  tomato: { singular: "tomato", plural: "tomatoes" },
  garlic: { singular: "garlic", plural: "garlic" },
  egg: { singular: "egg", plural: "eggs" },
  flour: { singular: "flour", plural: "flour" },
  sugar: { singular: "sugar", plural: "sugar" },
  salt: { singular: "salt", plural: "salt" },
  water: { singular: "water", plural: "water" },
  milk: { singular: "milk", plural: "milk" },
  bakingSoda: { singular: "baking soda", plural: "baking soda" },
  bakingPowder: { singular: "baking powder", plural: "baking powder" },
  yeast: { singular: "yeast", plural: "yeast" },
  whiteSugar: { singular: "white sugar", plural: "white sugar" },
  brownSugar: { singular: "brown sugar", plural: "brown sugar" },
  seaSalt: { singular: "sea salt", plural: "sea salt" },
  butter: { singular: "butter", plural: "butter" },
  oil: { singular: "oil", plural: "oil" },
  vegetableOil: { singular: "vegetable oil", plural: "vegetable oil" },
  oliveOil: { singular: "olive oil", plural: "olive oil" },
  vanillaExtract: { singular: "vanilla extract", plural: "vanilla extract" },
  lemonJuice: { singular: "lemon juice", plural: "lemon juice" },
  limeJuice: { singular: "lime juice", plural: "lime juice" },
  orangeJuice: { singular: "orange juice", plural: "orange juice" },
  lemonZest: { singular: "lemon zest", plural: "lemon zest" },
  limeZest: { singular: "lime zest", plural: "lime zest" },
  orangeZest: { singular: "orange zest", plural: "orange zest" },
  lemon: { singular: "lemon", plural: "lemons" },
  lime: { singular: "lime", plural: "limes" },
  orange: { singular: "orange", plural: "oranges" },
  apple: { singular: "apple", plural: "apples" },
  banana: { singular: "banana", plural: "bananas" },
  pear: { singular: "pear", plural: "pears" },
} as const;
