name: Check formatting, linting and TypeScript
on: push

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    container: node:18.18.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier:verify
  check-linting:
    runs-on: ubuntu-latest
    container: node:18.18.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint:verify
  check-typescript:
    runs-on: ubuntu-latest
    container: node:18.18.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run TypeScript
        run: npm run tsc
