name: Check linting
on: push

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    container: node:18.16.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint:verify
